# Generated by Django 6.0.4 on 2026-04-27 01:14

from django.db import migrations, models


def convert_tech_stack(apps, schema_editor):
    Project = apps.get_model('backend', 'Project')

    for project in Project.objects.all():
        value = project.tech_stack

        if isinstance(value, str):
            project.tech_stack = [
                tech.strip() for tech in value.split(',')
            ]
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Show this project in the portfolio'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Shows the green Live badge on the card'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shown first'),
        ),

        migrations.RunPython(convert_tech_stack),

        # then change field type
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(default=list, help_text="List of tech tags e.g. ['Python','Django','React']"),
        ),
    ]